# A sample Guardfile
# More info at https://github.com/guard/guard#readme


guard 'stitch-plus', config: '_config.yml' do
  watch %r{^js/|_config.yml}
end

guard "jekyll-plus" do
  watch /.*/
  ignore %r{^_site/}
end

