# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'stitch-plus', :dependencies => ['javascripts/dependencies/**/*'], :paths => ['javascripts/modules'] do
  watch /^javascripts/
end

