# A sample Guardfile
# More info at https://github.com/guard/guard#readme


# Add 
stitch_config = {
  dependencies: ['js/lib'],
  paths: ['js/modules'],
  output: 'js/site.js',
  uglify: true
}
guard 'stitch-plus', stitch_config do
  watch /js/
end


guard "jekyll-plus" do
  watch /.*/
  ignore %r{^_site/}
end

